### ISSUE TITLE
ograniczeczenie obciazenia systemu

### ISSUE THREAD

**Issue by twiniars** [RCPRG-ros-pkg/agent_orocos#1]
Problem dotyczy zasadniczej petli sterowania przechodzacej przez podsystemy (procesy) core agenta. Trzeba ograniczyc liczbe portow i komponentow, ktore sa w tej petli. Wydaje sie, ze praktycznym rozwiazaniem jest:
1. Przerzucenie konwersji typow danych w ramach zasadnicznej petli sterowania tylko i wylacznie do komponentow, ktore posredniczna w komunikacji pomiedzy procesami (deployarami).
2. Dla potrzeb diagnostyki (streamowania do ROS) nalezy powolywac komponenty w watkach poza petla sterowania. Dzieki temu nie bedziemy istotnie obiciazac tej petli.
2 a) Czy odpytywanie o stan podsystemu przez rqt_agent  za pomocą rosservice nie narusza pętli sterowania?

**Comment by dseredyn** [comment]
done
